// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StuMap.Context;

#nullable disable

namespace StuMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "E2845098-5312-4925-94B7-2ED3664CA318",
                            ConcurrencyStamp = "E2845098-5312-4925-94B7-2ED3664CA318",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "CB821695-B43A-41B9-8490-15A250D25FB5",
                            ConcurrencyStamp = "CB821695-B43A-41B9-8490-15A250D25FB5",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "2C4560E3-B816-43E5-8DA9-15C94336DC72",
                            ConcurrencyStamp = "2C4560E3-B816-43E5-8DA9-15C94336DC72",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "074B369D-5560-4ADA-99D2-F8AECF1E2423",
                            RoleId = "E2845098-5312-4925-94B7-2ED3664CA318"
                        },
                        new
                        {
                            UserId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            RoleId = "CB821695-B43A-41B9-8490-15A250D25FB5"
                        },
                        new
                        {
                            UserId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            RoleId = "2C4560E3-B816-43E5-8DA9-15C94336DC72"
                        },
                        new
                        {
                            UserId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            RoleId = "2C4560E3-B816-43E5-8DA9-15C94336DC72"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StuMap.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContributorStatus")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsContributorRequest")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoadmapId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            ContributorStatus = 1,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Email = "frankofoedu@contributor.com",
                            EmailConfirmed = true,
                            FirstName = "Frank",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Sinatra",
                            LockoutEnabled = false,
                            NormalizedEmail = "FRANKOFOEDU@CONTRIBUTOR.COM",
                            NormalizedUserName = "FRANKOFOEDU@CONTRIBUTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            TwoFactorEnabled = false,
                            UserName = "frankofoedu@contributor.com"
                        },
                        new
                        {
                            Id = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            ContributorStatus = 1,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Email = "amiraofoedu@contributor.com",
                            EmailConfirmed = true,
                            FirstName = "Amira",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Abdelaziz",
                            LockoutEnabled = false,
                            NormalizedEmail = "AMIRAOFOEDU@CONTRIBUTOR.COM",
                            NormalizedUserName = "AMIRAOFOEDU@CONTRIBUTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            TwoFactorEnabled = false,
                            UserName = "amiraofoedu@contributor.com"
                        },
                        new
                        {
                            Id = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            ContributorStatus = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Email = "faridaofoedu@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Farida",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Mohammed",
                            LockoutEnabled = false,
                            NormalizedEmail = "FARIDAOFOEDU@GMAIL.COM",
                            NormalizedUserName = "FARIDAOFOEDU@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            TwoFactorEnabled = false,
                            UserName = "faridaofoedu@gmail.com"
                        },
                        new
                        {
                            Id = "074B369D-5560-4ADA-99D2-F8AECF1E2423",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "074B369D-5560-4ADA-99D2-F8AECF1E2423",
                            ContributorStatus = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Email = "aadmin@stumap.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "AADMIN@STUMAP.COM",
                            NormalizedUserName = "AADMIN@STUMAP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "074B369D-5560-4ADA-99D2-F8AECF1E2423",
                            TwoFactorEnabled = false,
                            UserName = "admin@stumap.com"
                        },
                        new
                        {
                            Id = "3BD94FC0-7656-4EC5-9C8F-90897DD64BE5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3BD94FC0-7656-4EC5-9C8F-90897DD64BE5",
                            ContributorStatus = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@student.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMED@STUDENT.COM",
                            NormalizedUserName = "AHMED@STUDENT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3BD94FC0-7656-4EC5-9C8F-90897DD64BE5",
                            TwoFactorEnabled = false,
                            UserName = "ahmed@student.com"
                        },
                        new
                        {
                            Id = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            ContributorStatus = 1,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@contributor.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Ali",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@CONTRIBUTOR.COM",
                            NormalizedUserName = "SARA@CONTRIBUTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            TwoFactorEnabled = false,
                            UserName = "sara@contributor.com"
                        },
                        new
                        {
                            Id = "B9ECCC1E-FF12-41D0-9BE9-83B8A57EB855",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "B9ECCC1E-FF12-41D0-9BE9-83B8A57EB855",
                            ContributorStatus = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed@student.com",
                            EmailConfirmed = true,
                            FirstName = "Mohamed",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Ibrahim",
                            LockoutEnabled = false,
                            NormalizedEmail = "MOHAMED@STUDENT.COM",
                            NormalizedUserName = "MOHAMED@STUDENT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "B9ECCC1E-FF12-41D0-9BE9-83B8A57EB855",
                            TwoFactorEnabled = false,
                            UserName = "mohamed@student.com"
                        },
                        new
                        {
                            Id = "8CBAA357-F2D9-48FC-B4BC-27AD0BD7C1EB",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8CBAA357-F2D9-48FC-B4BC-27AD0BD7C1EB",
                            ContributorStatus = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatma@contributor.com",
                            EmailConfirmed = true,
                            FirstName = "Fatma",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Youssef",
                            LockoutEnabled = false,
                            NormalizedEmail = "FATMA@CONTRIBUTOR.COM",
                            NormalizedUserName = "FATMA@CONTRIBUTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8CBAA357-F2D9-48FC-B4BC-27AD0BD7C1EB",
                            TwoFactorEnabled = false,
                            UserName = "fatma@contributor.com"
                        },
                        new
                        {
                            Id = "E403198E-3791-46B5-8A8E-81F469A5B48E",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "E403198E-3791-46B5-8A8E-81F469A5B48E",
                            ContributorStatus = 2,
                            Country = "Egypt",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@student.com",
                            EmailConfirmed = true,
                            FirstName = "Omar",
                            IsBlocked = false,
                            IsContributorRequest = true,
                            LastName = "Khaled",
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR@STUDENT.COM",
                            NormalizedUserName = "OMAR@STUDENT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA1b94YdrgyUp6jDbQIM64vRSTjw7ojIiEqwPxWnXW5jegZQlfGGUF7/OgiO1Z0Lzw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "E403198E-3791-46B5-8A8E-81F469A5B48E",
                            TwoFactorEnabled = false,
                            UserName = "omar@student.com"
                        });
                });

            modelBuilder.Entity("StuMap.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ContributorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Approved = true,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Frontend Development Certificate",
                            Url = "https://example.com/certificates/frontend"
                        },
                        new
                        {
                            Id = 2,
                            Approved = true,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Data Science Certificate",
                            Url = "https://example.com/certificates/datascience"
                        },
                        new
                        {
                            Id = 3,
                            Approved = true,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Cybersecurity Fundamentals",
                            Url = "https://example.com/certificates/cybersecurity"
                        },
                        new
                        {
                            Id = 4,
                            Approved = true,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Mobile App Development",
                            Url = "https://example.com/certificates/mobile"
                        },
                        new
                        {
                            Id = 5,
                            Approved = true,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Cloud Computing with Azure",
                            Url = "https://example.com/certificates/cloud"
                        },
                        new
                        {
                            Id = 6,
                            Approved = true,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Artificial Intelligence",
                            Url = "https://example.com/certificates/ai"
                        },
                        new
                        {
                            Id = 8,
                            Approved = true,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "DevOps Practices",
                            Url = "https://example.com/certificates/devops"
                        },
                        new
                        {
                            Id = 9,
                            Approved = true,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Game Development with Unity",
                            Url = "https://example.com/certificates/game"
                        },
                        new
                        {
                            Id = 10,
                            Approved = true,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateIssued = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Title = "Networking Essentials",
                            Url = "https://example.com/certificates/networking"
                        });
                });

            modelBuilder.Entity("StuMap.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "I am having trouble understanding the material in the course.",
                            DateSent = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            IsRead = false,
                            Status = 2,
                            Subject = "Issue with course content",
                            UserId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89"
                        },
                        new
                        {
                            Id = 2,
                            Body = "I would like to see a dark mode option in the app.",
                            DateSent = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            IsRead = false,
                            Status = 0,
                            Subject = "Feature request",
                            UserId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89"
                        },
                        new
                        {
                            Id = 3,
                            Body = "The app crashes when I try to access my profile.",
                            DateSent = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            IsRead = false,
                            Status = 1,
                            Subject = "Bug report",
                            UserId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89"
                        },
                        new
                        {
                            Id = 4,
                            Body = "I can not accesss my saved Roadmaps.",
                            DateSent = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            IsRead = false,
                            Status = 1,
                            Subject = "Access Roadmap",
                            UserId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89"
                        },
                        new
                        {
                            Id = 5,
                            Body = "I am having trouble understanding the material in the course.",
                            DateSent = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            IsRead = false,
                            Status = 2,
                            Subject = "Issue with course content",
                            UserId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89"
                        });
                });

            modelBuilder.Entity("StuMap.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContributorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn the absolute basics of building web pages. Master the structure of a website using text elements, hyperlinks, forms, images, and semantic tags that help search engines understand your content.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to HTML5"
                        },
                        new
                        {
                            Id = 2,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            DateCreated = new DateTime(2026, 5, 16, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Transform plain text into beautiful, styled web pages. Discover colors, custom fonts, borders, margins, padding, and how to use selectors to target and style specific elements across your site.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Introduction to CSS3"
                        },
                        new
                        {
                            Id = 3,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            DateCreated = new DateTime(2026, 5, 15, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn how to make your websites look perfect on any screen size. Master modern layouts using CSS Flexbox and Grid, and use media queries to automatically adapt designs for mobile phones, tablets, and desktops.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Creating Responsive Web Designs"
                        },
                        new
                        {
                            Id = 4,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateCreated = new DateTime(2026, 5, 14, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Bring your static web pages to life with interactivity. Learn the fundamentals of programming—like variables, functions, and events—to handle user clicks, toggle menus, and create dynamic content.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Basic JavaScript for the Web"
                        },
                        new
                        {
                            Id = 5,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn Python basics, NumPy, and Pandas.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python for Data Science"
                        },
                        new
                        {
                            Id = 6,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Supervised and unsupervised learning algorithms.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning Basics"
                        },
                        new
                        {
                            Id = 7,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Network security, encryption, and ethical hacking.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Fundamentals"
                        },
                        new
                        {
                            Id = 8,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Cross-platform mobile apps using Flutter and Dart.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mobile App Development with Flutter"
                        },
                        new
                        {
                            Id = 9,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn Azure fundamentals and cloud-native services.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cloud Computing with Azure"
                        },
                        new
                        {
                            Id = 10,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Containerization, orchestration, and CI/CD pipelines.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "DevOps with Docker & Kubernetes"
                        },
                        new
                        {
                            Id = 11,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn Unity basics and build interactive games.",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game Development with Unity"
                        },
                        new
                        {
                            Id = 12,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn basics of network and Its layers",
                            IsDeleted = false,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Network Essentials"
                        });
                });

            modelBuilder.Entity("StuMap.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateEnrolled")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrollments");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            DateEnrolled = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            DateEnrolled = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = "B1364EFC-1779-4C6E-9623-0010F8F9EE89",
                            DateEnrolled = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StuMap.Models.CourseRoadmap", b =>
                {
                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("RoadmapId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseRoadmaps");

                    b.HasData(
                        new
                        {
                            RoadmapId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            RoadmapId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            RoadmapId = 1,
                            CourseId = 3
                        },
                        new
                        {
                            RoadmapId = 1,
                            CourseId = 4
                        },
                        new
                        {
                            RoadmapId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            RoadmapId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            RoadmapId = 2,
                            CourseId = 3
                        },
                        new
                        {
                            RoadmapId = 2,
                            CourseId = 4
                        },
                        new
                        {
                            RoadmapId = 4,
                            CourseId = 5
                        },
                        new
                        {
                            RoadmapId = 4,
                            CourseId = 6
                        },
                        new
                        {
                            RoadmapId = 5,
                            CourseId = 12
                        },
                        new
                        {
                            RoadmapId = 5,
                            CourseId = 7
                        },
                        new
                        {
                            RoadmapId = 6,
                            CourseId = 1
                        },
                        new
                        {
                            RoadmapId = 6,
                            CourseId = 2
                        },
                        new
                        {
                            RoadmapId = 6,
                            CourseId = 3
                        },
                        new
                        {
                            RoadmapId = 6,
                            CourseId = 4
                        },
                        new
                        {
                            RoadmapId = 6,
                            CourseId = 8
                        });
                });

            modelBuilder.Entity("StuMap.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContributorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("CourseId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 1,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "An authoritative, text-based guide by MDN Web Docs outlining elements, tags, attributes, and formatting requirements for standard web documents.",
                            MaterialTypeId = 1,
                            Title = "MDN Web Docs: Basic HTML Syntax",
                            Url = "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Basic_HTML_syntax"
                        },
                        new
                        {
                            Id = 2,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 1,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "An interactive web-based sandbox tool from W3Schools allowing you to write basic markup and instantly preview rendered headings, links, and text formatting.",
                            MaterialTypeId = 1,
                            Title = "W3Schools: HTML Tutorial",
                            Url = "https://www.w3schools.com/Html/"
                        },
                        new
                        {
                            Id = 3,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 1,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A comprehensive, four-hour structural video layout tutorial hosted on YouTube via freeCodeCamp designed to advance beginners through core content tagging.",
                            MaterialTypeId = 3,
                            Title = "freeCodeCamp: Learn HTML Full Tutorial for Beginners",
                            Url = "https://www.youtube.com/watch?v=kUMe1FH4CHE"
                        },
                        new
                        {
                            Id = 4,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 2,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A foundational guide on MDN Web Docs detailing cascade inheritance, standard syntax declarations, color applications, and fundamental font properties.",
                            MaterialTypeId = 1,
                            Title = "MDN Web Docs: CSS First Steps",
                            Url = "https://developer.mozilla.org/en-US/docs/Web/CSS"
                        },
                        new
                        {
                            Id = 5,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 2,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A focused structural design video playlist from freeCodeCamp demonstrating visual layout selectors, custom borders, elements padding, and style rules.",
                            MaterialTypeId = 3,
                            Title = "freeCodeCamp: CSS Tutorial – Full Course for Beginners",
                            Url = "https://www.youtube.com/watch?v=OXGznpKZ_sA"
                        },
                        new
                        {
                            Id = 6,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 2,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A modular web text environment via W3Schools with quick templates, text-align rules, custom backgrounds, and step-by-step styling exercises.",
                            MaterialTypeId = 1,
                            Title = "W3Schools: Online CSS Tutorials",
                            Url = "https://www.w3schools.com/css/"
                        },
                        new
                        {
                            Id = 7,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 3,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "An intensive project-based video on YouTube via SuperSimpleDev/freeCodeCamp mapping responsive website components and complex grid layouts.",
                            MaterialTypeId = 3,
                            Title = "freeCodeCamp: HTML & CSS Full Course - Beginner to Pro",
                            Url = "https://www.youtube.com/watch?v=G3e-cpL7ofc"
                        },
                        new
                        {
                            Id = 8,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 3,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "An instructional web framework guide by W3Schools showcasing dynamic viewport adjustments and screen-fluid grid column behaviors.",
                            MaterialTypeId = 1,
                            Title = "W3Schools: Build Responsive Sites with W3.CSS",
                            Url = "https://www.w3schools.com/css/"
                        },
                        new
                        {
                            Id = 9,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 4,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A technical deployment article from MDN Web Docs explaining script tag execution order, variable linkage, and element handling scripts.",
                            MaterialTypeId = 1,
                            Title = "MDN Web Docs: Adding JavaScript to an HTML File",
                            Url = "https://developer.mozilla.org/en-US/docs/Web/HTML"
                        },
                        new
                        {
                            Id = 10,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 4,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A comprehensive foundational video course on YouTube via freeCodeCamp exploring programmatic statements, custom functions, and interactive button bindings.",
                            MaterialTypeId = 3,
                            Title = "freeCodeCamp: Learn JavaScript Full Course for Beginners",
                            Url = "https://www.youtube.com/c/Freecodecamp"
                        },
                        new
                        {
                            Id = 11,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 4,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "A live programming sandbox on W3Schools providing quick snippets to modify document style properties dynamically via user clicks.",
                            MaterialTypeId = 1,
                            Title = "W3Schools: JavaScript Interactive Reference",
                            Url = "https://www.w3schools.com/js/"
                        },
                        new
                        {
                            Id = 12,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 1,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Introduction to HTML tags and structure.",
                            IsApproved = true,
                            MaterialTypeId = 1,
                            Title = "HTML Basics Article",
                            Url = "https://example.com/html-basics"
                        },
                        new
                        {
                            Id = 13,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            CourseId = 2,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn how to use flexbox for layouts.",
                            IsApproved = false,
                            MaterialTypeId = 2,
                            Title = "CSS Flexbox Video",
                            Url = "https://example.com/css-flexbox-video"
                        },
                        new
                        {
                            Id = 14,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 4,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Comprehensive guide to JavaScript basics.",
                            IsApproved = true,
                            MaterialTypeId = 3,
                            Title = "JavaScript Fundamentals Book",
                            Url = "https://example.com/js-fundamentals-book"
                        },
                        new
                        {
                            Id = 15,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 4,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Hands-on tutorial for Python data analysis.",
                            IsApproved = false,
                            MaterialTypeId = 1,
                            Title = "Python for Data Science Tutorial",
                            Url = "https://example.com/python-data-science"
                        },
                        new
                        {
                            Id = 16,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 6,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Exploring supervised learning algorithms.",
                            IsApproved = true,
                            MaterialTypeId = 6,
                            Title = "Machine Learning Research Paper",
                            Url = "https://example.com/ml-research-paper"
                        },
                        new
                        {
                            Id = 17,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 7,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Test your knowledge of cybersecurity basics.",
                            IsApproved = false,
                            MaterialTypeId = 6,
                            Title = "Cybersecurity Fundamentals Exam",
                            Url = "https://example.com/cybersecurity-exam"
                        },
                        new
                        {
                            Id = 18,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            CourseId = 8,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Build cross-platform apps with Flutter.",
                            IsApproved = true,
                            MaterialTypeId = 3,
                            Title = "Flutter Mobile Development Video",
                            Url = "https://example.com/flutter-video"
                        },
                        new
                        {
                            Id = 19,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            CourseId = 9,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Overview of Azure cloud services.",
                            IsApproved = false,
                            MaterialTypeId = 1,
                            Title = "Azure Cloud Presentation",
                            Url = "https://example.com/azure-presentation"
                        },
                        new
                        {
                            Id = 20,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            CourseId = 10,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Discussion on containerization and orchestration.",
                            IsApproved = true,
                            MaterialTypeId = 3,
                            Title = "Docker & Kubernetes Podcast",
                            Url = "https://example.com/devops-podcast"
                        },
                        new
                        {
                            Id = 21,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            CourseId = 11,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Visual guide to Unity interface.",
                            IsApproved = false,
                            MaterialTypeId = 4,
                            Title = "Unity Game Development Image",
                            Url = "https://example.com/unity-image"
                        },
                        new
                        {
                            Id = 22,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            CourseId = 12,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Explore all Network Types And learn How it works",
                            IsApproved = false,
                            MaterialTypeId = 4,
                            Title = "Network Types",
                            Url = "https://example.com/network-types"
                        },
                        new
                        {
                            Id = 23,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            CourseId = 12,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Explore all Network Layers And learn How it works",
                            IsApproved = false,
                            MaterialTypeId = 4,
                            Title = "Network Layers",
                            Url = "https://example.com/network-Layers"
                        },
                        new
                        {
                            Id = 24,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 5,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "python guide for beginners",
                            IsApproved = false,
                            MaterialTypeId = 4,
                            Title = "Python basics",
                            Url = "https://example.com/Python-basics"
                        },
                        new
                        {
                            Id = 25,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            CourseId = 5,
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn how to use NumPy in Python",
                            IsApproved = false,
                            MaterialTypeId = 4,
                            Title = "NumPy Library in Python",
                            Url = "https://example.com/Numpy"
                        });
                });

            modelBuilder.Entity("StuMap.Models.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Article"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Paper"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Video"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Image"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Book"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Exam"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Other"
                        });
                });

            modelBuilder.Entity("StuMap.Models.Roadmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContributorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Roadmaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Web development is the process of designing, building, and maintaining websites and web applications, combining both creative design and technical programming to deliver functional, user-friendly digital experiences. It includes front-end (what users see), back-end (server, database, logic), and full-stack (both sides) development",
                            IsApproved = false,
                            IsDeleted = false,
                            SpecializationId = 1,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Web development"
                        },
                        new
                        {
                            Id = 2,
                            ContributorId = "E2E368AB-8D20-401B-826A-F591202E3D19",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Frontend development focuses on everything the user sees and interacts with in the browser. It’s about turning design mockups (like the Figma prototype you have open) into functional, responsive, and engaging web pages.",
                            IsApproved = false,
                            IsDeleted = false,
                            SpecializationId = 2,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Frontend Path"
                        },
                        new
                        {
                            Id = 3,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Step-by-step guide to becoming a frontend developer.",
                            IsApproved = false,
                            IsDeleted = false,
                            SpecializationId = 1,
                            Status = 0,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Frontend Development Roadmap"
                        },
                        new
                        {
                            Id = 4,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn Python, statistics, and machine learning basics.",
                            IsApproved = false,
                            IsDeleted = false,
                            SpecializationId = 2,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Science Beginner Roadmap"
                        },
                        new
                        {
                            Id = 5,
                            ContributorId = "E746D970-DB04-4D42-9493-9173C7D13EE9",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Introduction to network security and ethical hacking.",
                            IsApproved = true,
                            IsDeleted = false,
                            SpecializationId = 3,
                            Status = 1,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Essentials"
                        },
                        new
                        {
                            Id = 6,
                            ContributorId = "EF8CCDB4-F6F5-4A89-BF18-E6E063271F67",
                            DateCreated = new DateTime(2026, 5, 17, 3, 29, 48, 808, DateTimeKind.Unspecified).AddTicks(706),
                            Description = "Learn Android and iOS development fundamentals.",
                            IsApproved = false,
                            IsDeleted = false,
                            SpecializationId = 4,
                            Status = 2,
                            SubmittedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mobile App Development Roadmap"
                        });
                });

            modelBuilder.Entity("StuMap.Models.RoadmapEnrollment", b =>
                {
                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateEnrolled")
                        .HasColumnType("datetime2");

                    b.HasKey("RoadmapId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("RoadmapEnrollment");
                });

            modelBuilder.Entity("StuMap.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Frontend and backend web technologies.",
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Machine learning, statistics, and data analysis.",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Protecting systems, networks, and data.",
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Building apps for Android and iOS.",
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = 5,
                            Description = "AWS, Azure, and cloud-native architectures.",
                            Name = "Cloud Computing"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Deep learning, NLP, and intelligent systems.",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Manual and automated testing practices.",
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = 8,
                            Description = "CI/CD pipelines, containerization, and automation.",
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Designing and programming interactive games.",
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Computer networks, protocols, and CCNA fundamentals.",
                            Name = "Networking"
                        });
                });

            modelBuilder.Entity("StuMap.Models.StudentRoadmapProgress", b =>
                {
                    b.Property<int>("RoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RoadmapEnrollmentRoadmapId")
                        .HasColumnType("int");

                    b.Property<string>("RoadmapEnrollmentStudentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoadmapId", "StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("RoadmapEnrollmentRoadmapId", "RoadmapEnrollmentStudentId");

                    b.ToTable("RoadmapsProgresses");
                });

            modelBuilder.Entity("StuMap.Models.UserDeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersDeviceTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StuMap.Models.ApplicationUser", b =>
                {
                    b.HasOne("StuMap.Models.Roadmap", null)
                        .WithMany("Students")
                        .HasForeignKey("RoadmapId");
                });

            modelBuilder.Entity("StuMap.Models.Certificate", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributorId");

                    b.Navigation("Contributor");
                });

            modelBuilder.Entity("StuMap.Models.Contact", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StuMap.Models.Course", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contributor");
                });

            modelBuilder.Entity("StuMap.Models.CourseEnrollment", b =>
                {
                    b.HasOne("StuMap.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StuMap.Models.CourseRoadmap", b =>
                {
                    b.HasOne("StuMap.Models.Course", "Course")
                        .WithMany("CourseRoadmaps")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.Roadmap", "Roadmap")
                        .WithMany("CourseRoadmaps")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("StuMap.Models.Material", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributorId");

                    b.HasOne("StuMap.Models.Course", "Course")
                        .WithMany("Materials")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StuMap.Models.MaterialType", "MaterialType")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Course");

                    b.Navigation("MaterialType");
                });

            modelBuilder.Entity("StuMap.Models.Roadmap", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StuMap.Models.Specialization", "Specialization")
                        .WithMany("Roadmaps")
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Contributor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("StuMap.Models.RoadmapEnrollment", b =>
                {
                    b.HasOne("StuMap.Models.Roadmap", "Roadmap")
                        .WithMany("Enrollments")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StuMap.Models.StudentRoadmapProgress", b =>
                {
                    b.HasOne("StuMap.Models.Course", "Course")
                        .WithMany("StudentRoadmapProgress")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StuMap.Models.RoadmapEnrollment", null)
                        .WithMany("StudentRoadmapProgress")
                        .HasForeignKey("RoadmapEnrollmentRoadmapId", "RoadmapEnrollmentStudentId");

                    b.Navigation("Course");

                    b.Navigation("Roadmap");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StuMap.Models.UserDeviceToken", b =>
                {
                    b.HasOne("StuMap.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StuMap.Models.Course", b =>
                {
                    b.Navigation("CourseRoadmaps");

                    b.Navigation("Materials");

                    b.Navigation("StudentRoadmapProgress");
                });

            modelBuilder.Entity("StuMap.Models.MaterialType", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("StuMap.Models.Roadmap", b =>
                {
                    b.Navigation("CourseRoadmaps");

                    b.Navigation("Enrollments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StuMap.Models.RoadmapEnrollment", b =>
                {
                    b.Navigation("StudentRoadmapProgress");
                });

            modelBuilder.Entity("StuMap.Models.Specialization", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
